version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: 437-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - 437-net

  backend:
    image: onrcanogul/437-api:prod
    container_name: 437-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - 437-net
    environment:
      SPRING_PROFILES_ACTIVE: prod

      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}


volumes:
  pgdata:

networks:
  437-net:
