name: CD - Deploy to Production Server

on:
  workflow_run:
    workflows: ["CI - Build & Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: >
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.head_branch == 'prod'
      }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy docker-compose.prod.yml
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          source: "./docker-compose.prod.yml"
          target: "/opt/437"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd /opt/437
            echo "Stop running services..."
            docker compose -f docker-compose.prod.yml down --remove-orphans || true
            
            echo "Pulling PROD image..."
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/437-api:prod
            
            echo "Starting new containers..."
            docker compose -f docker-compose.prod.yml --env-file .env.prod up -d
            
            echo "Production deploy complete!"
